# Generated by Django 4.2 on 2023-04-09 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esnileupgrade', '0004_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
